#!/usr/bin/env python3
"""
Generates the self-contained Kaggle notebook `training/karma_train_kaggle.ipynb`.
"""
import json
import os

NOTEBOOK_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "karma_train_kaggle.ipynb")
BUILD_DATASET_PY = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build_dataset.py")

with open(BUILD_DATASET_PY, "r", encoding="utf-8") as f:
    build_dataset_code = f.read()

cells = [
    # header
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Karma training: bilingual SFT + Q4_K_M GGUF\n",
            "\n",
            "Fine-tunes **Qwen 2.5 0.5B (or 1.5B) Instruct** on Karma's English + Egyptian Arabic (*عامية مصرية*) dataset, merges the LoRA weights, and exports a quantized **`Q4_K_M` GGUF** for the Raspberry Pi 4 / Mac / PC.\n",
            "\n",
            "- Dataset is ~1400 samples: persona (EN/AR), spontaneous thoughts + silence, vision grounding, beginner coding, general QA, refusals.\n",
            "- Loss is computed on assistant tokens only, so the small model doesn't learn to parrot prompts.\n",
            "- LoRA `r=16, alpha=32`, cosine schedule, lr `1e-4`.\n",
            "- Output is `karma-qwen2.5-0.5b-q4_k_m.gguf` (~350-400 MB).\n",
            "\n",
            "> In Kaggle: **Settings -> Accelerator -> GPU T4 x2** (or P100), Internet ON."
        ]
    },
    # deps
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# deps (no bitsandbytes: unused here, often fails to build on kaggle)\n",
            "!pip install -q -U torch transformers datasets peft trl accelerate sentencepiece gguf protobuf\n",
            "!apt-get update -qq && apt-get install -y -qq cmake build-essential git\n",
            "import importlib.metadata as _md\n",
            "for _pkg in [\"torch\", \"transformers\", \"datasets\", \"peft\", \"trl\", \"accelerate\"]:\n",
            "    try:\n",
            "        print(f\"{_pkg}=={_md.version(_pkg)}\")\n",
            "    except Exception:\n",
            "        print(f\"{_pkg}: version unknown\")\n",
            "print(\"deps installed\")"
        ]
    },
    # dataset markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Dataset\n",
            "Uses `train.jsonl` if it is already around (or under `/kaggle/input`), otherwise builds it from the embedded script."
        ]
    },
    # dataset code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# dataset\n",
            "import os\n",
            "import json\n",
            "import shutil\n",
            "import subprocess\n",
            "\n",
            "if not os.path.exists(\"train.jsonl\"):\n",
            "    for _cand in [\"/kaggle/input/karma-dataset/train.jsonl\", \"dataset/train.jsonl\"]:\n",
            "        if os.path.exists(_cand):\n",
            "            print(f\"found dataset at {_cand}, copying to ./train.jsonl\")\n",
            "            shutil.copy(_cand, \"train.jsonl\")\n",
            "            break\n",
            "\n",
            "if os.path.exists(\"train.jsonl\"):\n",
            "    print(\"found existing train.jsonl\")\n",
            "else:\n",
            "    print(\"building dataset...\")\n",
            "    with open(\"build_dataset.py\", \"w\", encoding=\"utf-8\") as f:\n",
            "        f.write('''" + build_dataset_code.replace("\\", "\\\\").replace("'''", "\\'\\'\\'") + "''')\n",
            "    subprocess.run([\"python3\", \"build_dataset.py\"], check=True)\n",
            "    if os.path.exists(\"dataset/train.jsonl\") and not os.path.exists(\"train.jsonl\"):\n",
            "        shutil.copy(\"dataset/train.jsonl\", \"train.jsonl\")\n",
            "\n",
            "with open(\"train.jsonl\", encoding=\"utf-8\") as _f:\n",
            "    _lines = _f.readlines()\n",
            "sample_count = len(_lines)\n",
            "print(f\"dataset ready: {sample_count} samples\")\n",
            "assert sample_count >= 1300, f\"expected 1300+ samples, got {sample_count}\"\n",
            "_prompts = [json.loads(_l)[\"messages\"][1][\"content\"] for _l in _lines]\n",
            "assert len(_prompts) == len(set(_prompts)), \"duplicate user prompts!\"\n",
            "print(\"prompts unique\")\n",
            "_roles = [tuple(_m[\"role\"] for _m in json.loads(_lines[0])[\"messages\"])]\n",
            "assert _roles[0] == (\"system\", \"user\", \"assistant\"), f\"unexpected roles: {_roles[0]}\"\n",
            "print(\"message format ok\")"
        ]
    },
    # model markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Model + LoRA\n",
            "`Qwen/Qwen2.5-0.5B-Instruct` (or 1.5B) in `bfloat16`, `float16` fallback on T4. LoRA on all projection layers."
        ]
    },
    # model code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# model + lora\n",
            "import os\n",
            "import torch\n",
            "from datasets import load_dataset\n",
            "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
            "from peft import LoraConfig, get_peft_model\n",
            "\n",
            "BASE_MODEL_NAME = \"Qwen/Qwen2.5-0.5B-Instruct\"  # or \"Qwen/Qwen2.5-1.5B-Instruct\"\n",
            "WORKING_DIR = \"/kaggle/working\" if os.path.isdir(\"/kaggle/working\") else \".\"\n",
            "OUTPUT_DIR = os.path.join(WORKING_DIR, \"karma-lora\")\n",
            "MERGED_DIR = os.path.join(WORKING_DIR, \"karma-merged\")\n",
            "MODEL_TAG = \"1.5b\" if \"1.5\" in BASE_MODEL_NAME else \"0.5b\"\n",
            "\n",
            "print(f\"loading tokenizer ({BASE_MODEL_NAME})...\")\n",
            "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_NAME, trust_remote_code=True)\n",
            "if tokenizer.pad_token is None:\n",
            "    tokenizer.pad_token = tokenizer.eos_token\n",
            "tokenizer.padding_side = \"right\"  # masking assumes prompt comes first\n",
            "\n",
            "dataset = load_dataset(\"json\", data_files=\"train.jsonl\", split=\"train\")\n",
            "print(f\"loaded {len(dataset):,} samples\")\n",
            "\n",
            "def apply_chat_template(batch):\n",
            "    formatted = []\n",
            "    for msgs in batch[\"messages\"]:\n",
            "        text = tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=False)\n",
            "        formatted.append(text)\n",
            "    return {\"text\": formatted}\n",
            "\n",
            "dataset = dataset.map(apply_chat_template, batched=True)\n",
            "_missing = sum(\"<|im_start|>assistant\" not in _t for _t in dataset[\"text\"])\n",
            "assert _missing == 0, f\"{_missing} samples missing the assistant header\"\n",
            "print(\"assistant header present in all samples\")\n",
            "\n",
            "split = dataset.train_test_split(test_size=0.05, seed=42)\n",
            "train_dataset, eval_dataset = split[\"train\"], split[\"test\"]\n",
            "print(f\"split: {len(train_dataset)} train / {len(eval_dataset)} eval\")\n",
            "\n",
            "# t4 has no bf16, fall back to fp16; `dtype` is new, `torch_dtype` is old\n",
            "HAS_CUDA = torch.cuda.is_available()\n",
            "USE_BF16 = HAS_CUDA and torch.cuda.is_bf16_supported()\n",
            "DTYPE = torch.bfloat16 if USE_BF16 else (torch.float16 if HAS_CUDA else torch.float32)\n",
            "device_map = \"auto\" if HAS_CUDA else {\"\": \"cpu\"}\n",
            "\n",
            "print(f\"loading {BASE_MODEL_NAME} ({DTYPE})...\")\n",
            "try:\n",
            "    model = AutoModelForCausalLM.from_pretrained(\n",
            "        BASE_MODEL_NAME,\n",
            "        dtype=DTYPE,\n",
            "        device_map=device_map,\n",
            "        trust_remote_code=True\n",
            "    )\n",
            "except TypeError:\n",
            "    model = AutoModelForCausalLM.from_pretrained(\n",
            "        BASE_MODEL_NAME,\n",
            "        torch_dtype=DTYPE,\n",
            "        device_map=device_map,\n",
            "        trust_remote_code=True\n",
            "    )\n",
            "model.config.use_cache = False\n",
            "\n",
            "lora_config = LoraConfig(\n",
            "    r=16,\n",
            "    lora_alpha=32,\n",
            "    target_modules=[\"q_proj\", \"k_proj\", \"v_proj\", \"o_proj\", \"gate_proj\", \"up_proj\", \"down_proj\"],\n",
            "    lora_dropout=0.05,\n",
            "    bias=\"none\",\n",
            "    task_type=\"CAUSAL_LM\"\n",
            ")\n",
            "model = get_peft_model(model, lora_config)\n",
            "model.print_trainable_parameters()"
        ]
    },
    # training code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# train (loss on assistant tokens only; collator vendored so any trl works)\n",
            "import torch\n",
            "from transformers import TrainingArguments\n",
            "\n",
            "USE_BF16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()\n",
            "USE_FP16 = torch.cuda.is_available() and not USE_BF16\n",
            "\n",
            "training_kwargs = dict(\n",
            "    output_dir=OUTPUT_DIR,\n",
            "    num_train_epochs=3,\n",
            "    per_device_train_batch_size=4,\n",
            "    per_device_eval_batch_size=4,\n",
            "    gradient_accumulation_steps=4,\n",
            "    learning_rate=1e-4,\n",
            "    lr_scheduler_type=\"cosine\",\n",
            "    warmup_ratio=0.05,\n",
            "    logging_steps=10,\n",
            "    save_strategy=\"epoch\",\n",
            "    eval_strategy=\"epoch\",\n",
            "    save_total_limit=2,\n",
            "    optim=\"adamw_torch\",\n",
            "    fp16=USE_FP16,\n",
            "    bf16=USE_BF16,\n",
            "    seed=42,\n",
            "    report_to=\"none\",\n",
            ")\n",
            "\n",
            "try:\n",
            "    from trl import SFTConfig\n",
            "    training_args = SFTConfig(max_length=1024, packing=False, **training_kwargs)\n",
            "    print(\"using SFTConfig\")\n",
            "except Exception as e:\n",
            "    print(f\"SFTConfig missing ({e}), falling back to TrainingArguments\")\n",
            "    training_args = TrainingArguments(**training_kwargs)\n",
            "\n",
            "from transformers import DataCollatorForLanguageModeling\n",
            "\n",
            "RESPONSE_TEMPLATE = \"<|im_start|>assistant\\n\"\n",
            "_resp_ids = tokenizer.encode(RESPONSE_TEMPLATE, add_special_tokens=False)\n",
            "print(f\"response template ids: {_resp_ids}\")\n",
            "\n",
            "def _find_sublist(haystack, needle):\n",
            "    n, m = len(haystack), len(needle)\n",
            "    for i in range(n - m + 1):\n",
            "        if haystack[i:i + m] == needle:\n",
            "            return i\n",
            "    return -1\n",
            "\n",
            "class CompletionOnlyCollator(DataCollatorForLanguageModeling):\n",
            "    def __init__(self, tokenizer, mlm=False):\n",
            "        super().__init__(tokenizer=tokenizer, mlm=mlm)\n",
            "        self.resp_ids = _resp_ids\n",
            "\n",
            "    def torch_call(self, examples):\n",
            "        batch = super().torch_call(examples)\n",
            "        labels = batch[\"labels\"].clone()\n",
            "        for i in range(labels.size(0)):\n",
            "            ids = batch[\"input_ids\"][i].tolist()\n",
            "            idx = _find_sublist(ids, self.resp_ids)\n",
            "            if idx == -1:\n",
            "                if not getattr(self, \"_warned\", False):\n",
            "                    print(\"warning: response template missing in a sample, keeping full loss for it\")\n",
            "                    self._warned = True\n",
            "                continue\n",
            "            cutoff = idx + len(self.resp_ids)\n",
            "            labels[i, :cutoff] = -100\n",
            "        batch[\"labels\"] = labels\n",
            "        return batch\n",
            "\n",
            "collator = CompletionOnlyCollator(tokenizer=tokenizer, mlm=False)\n",
            "\n",
            "def _tokenize_fn(batch):\n",
            "    return tokenizer(batch[\"text\"], truncation=True, max_length=1024)\n",
            "\n",
            "tokenized_train = train_dataset.map(_tokenize_fn, batched=True, remove_columns=[\"messages\", \"text\"])\n",
            "tokenized_eval = eval_dataset.map(_tokenize_fn, batched=True, remove_columns=[\"messages\", \"text\"])\n",
            "\n",
            "from trl import SFTTrainer\n",
            "import inspect as _inspect\n",
            "_sig = _inspect.signature(SFTTrainer.__init__)\n",
            "if \"processing_class\" in _sig.parameters:\n",
            "    trainer = SFTTrainer(\n",
            "        model=model,\n",
            "        args=training_args,\n",
            "        train_dataset=tokenized_train,\n",
            "        eval_dataset=tokenized_eval,\n",
            "        data_collator=collator,\n",
            "        processing_class=tokenizer,\n",
            "    )\n",
            "else:\n",
            "    trainer = SFTTrainer(\n",
            "        model=model,\n",
            "        train_dataset=train_dataset,\n",
            "        eval_dataset=eval_dataset,\n",
            "        dataset_text_field=\"text\",\n",
            "        max_seq_length=1024,\n",
            "        tokenizer=tokenizer,\n",
            "        data_collator=collator,\n",
            "        args=training_args,\n",
            "    )\n",
            "\n",
            "print(\"training...\")\n",
            "trainer.train()\n",
            "\n",
            "print(f\"saving adapter to {OUTPUT_DIR}...\")\n",
            "trainer.model.save_pretrained(OUTPUT_DIR)\n",
            "tokenizer.save_pretrained(OUTPUT_DIR)\n",
            "print(\"adapter saved\")"
        ]
    },
    # eval code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# quick check on a few prompts\n",
            "import torch\n",
            "\n",
            "test_prompts = [\n",
            "    (\"English Persona\", \"What's up, Karma?\"),\n",
            "    (\"Egyptian Arabic Persona\", \"إزيك يا كارما عامل إيه النهاردة؟\"),\n",
            "    (\"Beginner Coding\", \"ازاي ارتب مصفوفة في بايثون؟\"),\n",
            "    (\"Spontaneous Observation\", \"Current Environment: coffee cup, laptop\\nWhat should I do right now?\")\n",
            "]\n",
            "\n",
            "model.eval()\n",
            "try:\n",
            "    _device = model.device\n",
            "except Exception:\n",
            "    try:\n",
            "        _device = next(model.parameters()).device\n",
            "    except Exception:\n",
            "        _device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(f\"device: {_device}\")\n",
            "\n",
            "for category, user_query in test_prompts:\n",
            "    sys_prompt = (\n",
            "        \"أنت كارما، روبوت وصاحب جدع ورايق في الأوضة. ردودك ديماً قصيرة (جملة أو جملتين) بالعامية المصرية.\"\n",
            "        if any('\\u0600' <= c <= '\\u06ff' for c in user_query)\n",
            "        else \"You are Karma, a witty, chill friend hanging out in the room. Keep replies brief (1-2 sentences).\"\n",
            "    )\n",
            "    messages = [\n",
            "        {\"role\": \"system\", \"content\": sys_prompt},\n",
            "        {\"role\": \"user\", \"content\": user_query}\n",
            "    ]\n",
            "    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n",
            "    inputs = tokenizer(prompt, return_tensors=\"pt\")\n",
            "    inputs = {k: v.to(_device) for k, v in inputs.items()}\n",
            "    with torch.no_grad():\n",
            "        outputs = model.generate(\n",
            "            **inputs,\n",
            "            max_new_tokens=100,\n",
            "            do_sample=True,\n",
            "            temperature=0.7,\n",
            "            top_p=0.9,\n",
            "            repetition_penalty=1.1,\n",
            "            eos_token_id=tokenizer.eos_token_id,\n",
            "            pad_token_id=tokenizer.pad_token_id,\n",
            "        )\n",
            "    reply = tokenizer.decode(outputs[0][inputs[\"input_ids\"].shape[1]:], skip_special_tokens=False)\n",
            "    reply = reply.split(\"<|im_end|>\")[0].replace(\"<|endoftext|>\", \"\").strip()\n",
            "    print(f\"\\n[{category}]\")\n",
            "    print(f\"User:  {user_query}\")\n",
            "    print(f\"Karma: {reply.strip()}\")"
        ]
    },
    # merge code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# merge lora back into the base model\n",
            "import gc\n",
            "import torch\n",
            "\n",
            "print(f\"merging into {MERGED_DIR}...\")\n",
            "merged_model = model.merge_and_unload()\n",
            "merged_model.save_pretrained(MERGED_DIR)\n",
            "tokenizer.save_pretrained(MERGED_DIR)\n",
            "print(f\"merged model at {MERGED_DIR}\")\n",
            "\n",
            "del model\n",
            "del merged_model\n",
            "gc.collect()\n",
            "if torch.cuda.is_available():\n",
            "    torch.cuda.empty_cache()"
        ]
    },
    # gguf markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## GGUF (Q4_K_M)\n",
            "Build `llama-quantize`, convert the merged model to f16 GGUF, quantize down. Output runs on the Pi."
        ]
    },
    # gguf code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# gguf conversion + quantization\n",
            "import os\n",
            "import shutil\n",
            "import subprocess\n",
            "\n",
            "WORKING_DIR = \"/kaggle/working\" if os.path.isdir(\"/kaggle/working\") else \".\"\n",
            "LLAMA_CPP_DIR = os.path.join(WORKING_DIR, \"llama.cpp\")\n",
            "MODEL_TAG = \"1.5b\" if \"1.5\" in BASE_MODEL_NAME else \"0.5b\"\n",
            "FINAL_GGUF = os.path.join(WORKING_DIR, f\"karma-qwen2.5-{MODEL_TAG}-q4_k_m.gguf\")\n",
            "INTERMEDIATE_GGUF = os.path.join(WORKING_DIR, \"karma-f16.gguf\")\n",
            "\n",
            "def run(cmd, **kwargs):\n",
            "    print(f\"$ {' '.join(cmd)}\")\n",
            "    subprocess.run(cmd, check=True, **kwargs)\n",
            "\n",
            "if not os.path.isdir(LLAMA_CPP_DIR):\n",
            "    print(\"cloning llama.cpp...\")\n",
            "    run([\"git\", \"clone\", \"--depth\", \"1\", \"https://github.com/ggml-org/llama.cpp.git\", LLAMA_CPP_DIR])\n",
            "else:\n",
            "    print(f\"reusing {LLAMA_CPP_DIR}\")\n",
            "\n",
            "print(\"installing llama.cpp requirements...\")\n",
            "run([\"pip\", \"install\", \"-q\", \"-r\", os.path.join(LLAMA_CPP_DIR, \"requirements.txt\")])\n",
            "\n",
            "print(\"building llama-quantize...\")\n",
            "run([\"cmake\", \"-B\", os.path.join(LLAMA_CPP_DIR, \"build\"), \"-DLLAMA_CURL=OFF\"], cwd=LLAMA_CPP_DIR)\n",
            "run([\"cmake\", \"--build\", os.path.join(LLAMA_CPP_DIR, \"build\"), \"--config\", \"Release\", \"-t\", \"llama-quantize\", \"-j\", \"4\"], cwd=LLAMA_CPP_DIR)\n",
            "\n",
            "# binary moved around between releases, check a few spots\n",
            "_candidates = [\n",
            "    os.path.join(LLAMA_CPP_DIR, \"build\", \"bin\", \"llama-quantize\"),\n",
            "    os.path.join(LLAMA_CPP_DIR, \"build\", \"bin\", \"quantize\"),\n",
            "    os.path.join(LLAMA_CPP_DIR, \"llama-quantize\"),\n",
            "    os.path.join(LLAMA_CPP_DIR, \"build\", \"llama-quantize\"),\n",
            "    shutil.which(\"llama-quantize\"),\n",
            "]\n",
            "QUANT_BIN = next((p for p in _candidates if p and os.path.exists(p)), None)\n",
            "assert QUANT_BIN is not None, \"llama-quantize not found, check cmake output\"\n",
            "print(f\"quantize binary: {QUANT_BIN}\")\n",
            "\n",
            "CONVERT_SCRIPT = os.path.join(LLAMA_CPP_DIR, \"convert_hf_to_gguf.py\")\n",
            "assert os.path.exists(CONVERT_SCRIPT), f\"missing {CONVERT_SCRIPT}\"\n",
            "assert os.path.isdir(MERGED_DIR), f\"no merged model at {MERGED_DIR}\"\n",
            "print(f\"converting to f16 gguf...\")\n",
            "run([\"python3\", CONVERT_SCRIPT, MERGED_DIR, \"--outfile\", INTERMEDIATE_GGUF, \"--outtype\", \"f16\"])\n",
            "assert os.path.exists(INTERMEDIATE_GGUF), \"conversion produced no file\"\n",
            "\n",
            "print(f\"quantizing to Q4_K_M...\")\n",
            "run([QUANT_BIN, INTERMEDIATE_GGUF, FINAL_GGUF, \"Q4_K_M\"])\n",
            "assert os.path.exists(FINAL_GGUF), \"quantization produced no file\"\n",
            "\n",
            "if os.path.exists(INTERMEDIATE_GGUF):\n",
            "    os.remove(INTERMEDIATE_GGUF)\n",
            "print(\"quantization done\")"
        ]
    },
    # done code
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# done — download the file below\n",
            "import os\n",
            "from IPython.display import FileLink, display\n",
            "\n",
            "WORKING_DIR = \"/kaggle/working\" if os.path.isdir(\"/kaggle/working\") else \".\"\n",
            "MODEL_TAG = \"1.5b\" if \"1.5\" in BASE_MODEL_NAME else \"0.5b\"\n",
            "FINAL_GGUF = os.path.join(WORKING_DIR, f\"karma-qwen2.5-{MODEL_TAG}-q4_k_m.gguf\")\n",
            "FINAL_NAME = os.path.basename(FINAL_GGUF)\n",
            "\n",
            "if os.path.exists(FINAL_GGUF):\n",
            "    size_mb = os.path.getsize(FINAL_GGUF) / (1024 * 1024)\n",
            "    with open(FINAL_GGUF, \"rb\") as _f:\n",
            "        _magic = _f.read(4)\n",
            "    assert _magic == b\"GGUF\", f\"bad magic: {_magic!r}\"\n",
            "    print(f\"ready: {FINAL_GGUF} ({size_mb:.1f} MB)\")\n",
            "    print(f\"download it, then: cp {FINAL_NAME} models/model.gguf && python3 main.py\")\n",
            "    display(FileLink(FINAL_GGUF))\n",
            "else:\n",
            "    print(\"gguf not found, check the logs above\")"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "accelerator": "GPU",
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.10.12"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(NOTEBOOK_PATH, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"wrote {NOTEBOOK_PATH}")
